version: "3.8"

services:

  django:
    &django
    build:
      context: .
      dockerfile: compose/Dockerfile-django
    volumes:
      - ./with_ranges:/app
      # - ./templates:/app/templates
      # - ./static:/app/static
    user: 1000:1000
    command:
      [
        "sh",
        "-c",
        "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver_plus 0.0.0.0:8002"
      ]
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - postgres
      - redis
    networks:
      - with_ranges
    ports:
      # host-port:container-port
      - "8002:8002"
      - "5679:5679"

  celery:
    <<: *django
    command: celery -A config worker -l INFO
    depends_on:
      - django
      - redis
    ports: []

  postgres:
    build:
      context: .
      dockerfile: ./compose/Dockerfile-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresdata_with_ranges:/var/lib/postgresql/data/
    networks:
      - with_ranges
    ports:
      # Make postgres available on the host at 127.0.0.1:5463
      - "5463:5432"

  redis:
    image: "redis:alpine"
    networks:
      - with_ranges

volumes:
  postgresdata_with_ranges:


networks:
  with_ranges:
