FROM postgres:14

RUN apt-get update && apt-get -y install git build-essential postgresql-contrib-14 -y

# Copy over the sql file which runs CREATE EXTENSION
COPY ./compose/extensions.sql /docker-entrypoint-initdb.d/
